### ISSUE TITLE
Questions About Assignment 2 

### ISSUE THREAD

**Issue by ginalee0122** [qidizhai/bme590hrm#9]
About .csv input file:
- How are the information on the voltage and time organized in each line?
- Where in the file (e.g. at the last line of the file) is the information on the threshold values of bradycardia or tachycardia?
- Is there any data we should throw away or not consider? For example, the first 10 seconds of data is invalid? (Except for the fact that the first line is a comment)
- Where is the information on calculating instantaneous heart rate (dBeats/dTime) and how is it formatted? 

About the output file:
- What is the order and format of the 3 components we should output?

**Comment by mlp6** [comment]
1. That was specified in the assignment; it is a CSV file with time (s) and voltage (mV) (e.g., 0.1, 0.5)
2. The input data does not contain threshold information; that is for you to choose and expose as a user input (could have default values that can be overridden).
3. All data are fair game
4. Your need to calculate instantaneous HR using an algorithm of your choice
5. Output file format is not specified; your choice.
